[15:56:22] [ERROR] [140295708493568] debug: now_length = 6; length = 16;
[15:56:23] [ERROR] [140296289502976] https://wiki.hduisa.cn @@ requests fail and the info is hostname 'wiki.hduisa.cn' doesn't match either of 'lightless.me', 'www.lightless.me'
[15:56:25] [ERROR] [140295690901248] debug: now_length = 166; length = 176;
[15:56:29] [ERROR] [140296553596672] http://zanshimeiyoutianshang.com @@ requests fail and the info is HTTPConnectionPool(host='zanshimeiyoutianshang.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9922d63e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[15:56:32] [ERROR] [140296545203968] http://www.hustdba.com/?p=145 @@ requests fail and the info is HTTPConnectionPool(host='www.hustdba.com', port=80): Max retries exceeded with url: /?p=145 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9922d63a50>, 'Connection to www.hustdba.com timed out. (connect timeout=4)'))
[15:56:32] [ERROR] [140296281110272] http://zh_explorer.gitcafe.io/2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ @@ requests fail and the info is HTTPConnectionPool(host='zh_explorer.gitcafe.io', port=80): Max retries exceeded with url: /2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9922d7e3d0>, 'Connection to zh_explorer.gitcafe.io timed out. (connect timeout=4)'))
[15:56:32] [ERROR] [140296289502976] http://zh_explorer.gitcafe.io/2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ @@ requests fail and the info is HTTPConnectionPool(host='zh_explorer.gitcafe.io', port=80): Max retries exceeded with url: /2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9922d63a90>, 'Connection to zh_explorer.gitcafe.io timed out. (connect timeout=4)'))
[15:56:33] [ERROR] [140296314681088] http://code.woboq.org/userspace/glibc/malloc/malloc.c.html @@ requests fail and the info is HTTPConnectionPool(host='code.woboq.org', port=80): Max retries exceeded with url: /userspace/glibc/malloc/malloc.c.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f99224e30d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
[15:56:35] [ERROR] [140295690901248] debug: now_length = 94; length = 166;
[15:56:38] [ERROR] [140296297895680] http://code.woboq.org/userspace/glibc/malloc/malloc.c.html @@ requests fail and the info is HTTPSConnectionPool(host='code.woboq.org', port=443): Read timed out. (read timeout=4)
[15:56:45] [ERROR] [140295690901248] debug: now_length = 48; length = 94;
[15:56:50] [ERROR] [140296314681088] http://blog.golemon.com/2008/01/understanding-opcodes.html @@ requests fail and the info is HTTPConnectionPool(host='blog.golemon.com', port=80): Max retries exceeded with url: /2008/01/understanding-opcodes.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f99440a88d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
[15:56:51] [ERROR] [140296289502976] https://twitter.com/gosecure_inc @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /gosecure_inc (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f99440a8c50>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:56:52] [ERROR] [140296314681088] http://secflaw.wordpress.com @@ requests fail and the info is ('Connection aborted.', error(104, 'Connection reset by peer'))
[15:56:55] [ERROR] [140295690901248] debug: now_length = 0; length = 48;
[15:56:55] [ERROR] [140296306288384] https://twitter.com/share @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /share (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f99440a8590>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:56:56] [ERROR] [140296314681088] https://twitter.com/hexojs @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /hexojs (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9944032a10>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:56:56] [ERROR] [140296297895680] https://twitter.com/hexojs @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /hexojs (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9944032050>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:58:54] [ERROR] [139960300599040] debug: now_length = 6; length = 16;
[15:58:55] [ERROR] [139960669681408] https://wiki.hduisa.cn @@ requests fail and the info is hostname 'wiki.hduisa.cn' doesn't match either of 'lightless.me', 'www.lightless.me'
[15:59:02] [ERROR] [139961082971904] http://blog.gosecure.ca/2016/05/26/detecting-hidden-backdoors-in-php-opcache/ @@ requests fail and the info is HTTPConnectionPool(host='blog.gosecure.ca', port=80): Max retries exceeded with url: /2016/05/26/detecting-hidden-backdoors-in-php-opcache/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b380bf5d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
[15:59:02] [ERROR] [139961057793792] http://blog.gosecure.ca/2016/04/27/binary-webshell-through-opcache-in-php-7/ @@ requests fail and the info is HTTPConnectionPool(host='blog.gosecure.ca', port=80): Max retries exceeded with url: /2016/04/27/binary-webshell-through-opcache-in-php-7/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b381889d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
[15:59:02] [ERROR] [139960286873344] debug: now_length = 128; length = 138;
[15:59:03] [ERROR] [139961074579200] http://zanshimeiyoutianshang.com @@ requests fail and the info is HTTPConnectionPool(host='zanshimeiyoutianshang.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b0b315190>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[15:59:06] [ERROR] [139960703252224] http://zh_explorer.gitcafe.io/2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ @@ requests fail and the info is HTTPConnectionPool(host='zh_explorer.gitcafe.io', port=80): Max retries exceeded with url: /2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b0b315450>, 'Connection to zh_explorer.gitcafe.io timed out. (connect timeout=4)'))
[15:59:07] [ERROR] [139961066186496] http://zh_explorer.gitcafe.io/2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ @@ requests fail and the info is HTTPConnectionPool(host='zh_explorer.gitcafe.io', port=80): Max retries exceeded with url: /2015/08/06/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86%E4%B8%ADfree%E7%9A%84%E8%A1%8C%E4%B8%BA/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b20038e90>, 'Connection to zh_explorer.gitcafe.io timed out. (connect timeout=4)'))
[15:59:11] [ERROR] [139961074579200] http://www.hustdba.com/?p=145 @@ requests fail and the info is HTTPConnectionPool(host='www.hustdba.com', port=80): Max retries exceeded with url: /?p=145 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b20045950>, 'Connection to www.hustdba.com timed out. (connect timeout=4)'))
[15:59:12] [ERROR] [139960286873344] debug: now_length = 57; length = 128;
[15:59:22] [ERROR] [139960286873344] debug: now_length = 19; length = 57;
[15:59:29] [ERROR] [139961074579200] https://zespia.tw/ @@ requests fail and the info is HTTPSConnectionPool(host='zespia.tw', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b0b328c10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
[15:59:29] [ERROR] [139961057793792] http://creativecommons.org/licenses/by/4.0/ @@ requests fail and the info is HTTPConnectionPool(host='creativecommons.org', port=80): Read timed out. (read timeout=4)
[15:59:31] [ERROR] [139961066186496] https://twitter.com/share @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /share (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b0b2f6e10>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:59:31] [ERROR] [139960703252224] https://twitter.com/hexojs @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /hexojs (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b2002a5d0>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:59:31] [ERROR] [139960669681408] https://twitter.com/hexojs @@ requests fail and the info is HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /hexojs (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b2002a4d0>, 'Connection to twitter.com timed out. (connect timeout=4)'))
[15:59:32] [ERROR] [139960286873344] debug: now_length = 0; length = 19;
